// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OpenCampus.API.Data;
using OpenCampus.API.Data.Extensions;

#nullable disable

namespace OpenCampus.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240219000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.ApplyConfigurationsFromAssembly(typeof(ApplicationDbContext).Assembly);
            modelBuilder.ApplyAuditableEntityDefaults();
            modelBuilder.ApplyRestrictDeleteBehavior();
        }
    }
}
